# NASA AI Model Configuration

# Model Settings
model:
  base_model: "microsoft/DialoGPT-medium"
  output_dir: "./nasa-model"
  trained_model_path: "./nasa-model/final_model"
  max_length: 512
  temperature: 0.7
  top_k: 50
  top_p: 0.9
  repetition_penalty: 1.2

# Training Settings
training:
  num_epochs: 2
  batch_size: 2
  learning_rate: 5e-5
  warmup_steps: 100
  weight_decay: 0.01
  max_steps: 1000
  save_steps: 500
  logging_steps: 50

# Data Settings
data:
  papers_file: "../all_papers_chunked.jsonl"
  taskbook_file: "../Taskbook_cleaned_for_NLP.csv"
  max_chunk_length: 500
  min_chunk_length: 50

# RAG Settings
rag:
  embedding_model: "all-MiniLM-L6-v2"
  top_k_results: 5
  similarity_threshold: 0.7
  index_type: "IndexFlatIP"

# API Settings
api:
  host: "127.0.0.1"
  port: 8001
  workers: 1
  reload: true

# Gradio Settings
gradio:
  host: "127.0.0.1"
  port: 7860
  share: false
  debug: false
